const LANGUAGE = `language`;
const AUCTION_SHARED_RENTAL = 'AUCTION_SHARED_RENTAL';
const GOLF_RESER_CHAT_DATA = 'GOLF_RESER_CHAT_DATA';
const RESERVATION_DATA = 'ReservationData';
const SALE_DATA = 'SaleData';
const RENTAL_DATA = 'RentalData';
const MY_PAGE_GOLF_RES_SELECT_CHAT = 'MypageGolfResSelectChat';
const HOME_SEARCH = 'homeSearch';
const FILTERPRICE = 'FILTERPRICE'
const SHEET_POSITION = ' SHEET_POSITION'
const FILTERTYPE = 'FILTERTYPE'
export {
  LANGUAGE,
  AUCTION_SHARED_RENTAL,
  GOLF_RESER_CHAT_DATA,
  RESERVATION_DATA,
  SALE_DATA,
  RENTAL_DATA,
  MY_PAGE_GOLF_RES_SELECT_CHAT,
  HOME_SEARCH,
  FILTERPRICE,
  FILTERTYPE,
  SHEET_POSITION
};
